@PokedexApp.Server_HostAddress = http://localhost:5264

GET {{PokedexApp.Server_HostAddress}}/api/Pokemon/pikachu
Accept: application/json

###

GET {{PokedexApp.Server_HostAddress}}/api/Pokemon/NotAPokemonName
Accept: application/json

###
